version: '2'

services:

  api-campaign:
    build: .
    container_name: api-campaign
    volumes:
      - ./:/api-campaign
    ports:
      - 8080:8080
    depends_on:
      - storage

  storage:
    image: mongo:3.4
    ports:
      - 27017:27017
